language: rust
sudo: false
dist: bionic
addons:
    apt:
        packages:
            - libssl-dev
rust:
  - 1.36.0
  - 1.37.0
  - stable
  - beta
  - nightly
cache: cargo
before_script: |
  if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then
    cargo install cargo-tarpaulin
  fi
script:
  - cargo build --verbose --no-default-features
  - cargo test --verbose --no-default-features
  - cargo build --verbose
  - cargo test --verbose
after_success: |
  if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then
    cargo tarpaulin --verbose --exclude-files benches/*.rs --ciserver travis-ci --coveralls $TRAVIS_JOB_ID
  fi
