[package]
name = "z80emu"
description = "A minimalistic Z80 Cpu emulator library"
version = "0.0.1"
authors = ["Rafał Michalski <royaltm75@gmail.com>"]
edition = "2018"
repository = "https://github.com/royaltm/rust-z80emu"

readme = "README.md"
keywords = ["Z80", "retro"]
categories = ["emulators", "no-std"]
license-file = "LICENSE.md"

[features]
default = ["std", "serde"]
std = ["serde/std"]

[dependencies]
bitflags = "1.2.1"
log = "0.4.8"
arrayvec = "0.4.11"

[dependencies.serde]
version = "1.0"
optional = true
default-features = false
features = ["derive"]

[dev-dependencies]
clap = "2.33"
serde_json = "1.0"
simplelog = "0.7.3"
rand = "0.7"
pancurses = {version = "0.16"}
