[package]
name = "z80emu"
version = "0.1.0"
authors = ["Rafal Michalski <royal@yeondir.com>"]
edition = "2018"

[dependencies]
# derive_more = "^0.15"
bitflags = "1.1.0"
log = "0.4.8"
arrayvec = "0.4.11"
serde = { version = "1.0", features = ["derive"] }
# static_assertions = "0.3.4"

[dev-dependencies]
serde_json = "1.0"
simple_logger = "1.3.0"
rand = "^0.7"

# [profile.release]
# lto = true
# panic = 'abort'
# opt-level = 3
