name: Continuous integration

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    continue-on-error: false
    strategy:
      matrix:
        os: 
          - ubuntu-latest
          - windows-latest
          - macos-latest
        rust:
          - 1.51.0
          - stable
          - beta
          - nightly
        include:
          - os: ubuntu-latest
          - rust: stable
          - coverage: true
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Install ${{ matrix.rust }} toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain:  ${{ matrix.rust }}
          override: true
      - name: Tests
        run: |
          cargo build --verbose --no-default-features
          cargo test --verbose --no-default-features
          cargo build --verbose
          cargo test --verbose
      - name: Coverage
        if: matrix.coverage
        uses: actions-rs/tarpaulin@v0.1
        with:
          version: 'latest'
          args: --verbose --exclude-files benches/*.rs --coveralls ${{secrets.COVERALLS_KEY}}
